---
- hosts: all
  sudo: yes
  tasks:

    - name: adding GPG for RVM
      shell: gpg --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3

    - name: remove ruby from ubuntu
      apt: name=ruby state=absent purge=yes

    - name: add java repo keys
      apt_key: keyserver=keyserver.ubuntu.com id=EEA14886 state=present

    - name: add java repo
      apt_repository: repo='deb http://ppa.launchpad.net/webupd8team/java/ubuntu precise main' state=present

    - name: add java sources repo
      apt_repository: repo='deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu precise main' state=present

    - name: accept java license
      debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

    - name: install java 8
      apt: name=oracle-java8-installer update_cache=yes state=present

    - name: install apt packages
      apt: name="{{ item }}" state=present
      with_items:
        - vim
        - npm
        - screen
        - python-pip
        - unzip
        - mysql-client
        - make

    - name: download maven
      get_url: url=http://ftp.unicamp.br/pub/apache/maven/maven-3/3.2.1/binaries/apache-maven-3.2.1-bin.tar.gz dest=/opt/

    - name: unarchive maven
      unarchive: src=/opt/apache-maven-3.2.1-bin.tar.gz dest=/opt/ copy=no

    - name: symlink maven dir
      file: src=/opt/apache-maven-3.2.1 dest=/opt/maven state=link

    - name: symlink maven bin
      file: src=/opt/maven/bin/mvn dest=/usr/bin/mvn state=link

    - name: add mysql client config
      template: src=templates/my.cnf dest=/etc/my.cnf owner=root group=root mode=644

- hosts: all
  sudo: no
  user: vagrant
  tasks:

    - name: install rvm
      shell: curl -L https://get.rvm.io | bash -s stable creates=~/.rvm

    - name: install foreman
      gem: name=foreman state=latest executable=/opt/vagrant_ruby/bin/gem


